// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IEpCaretLeft: typeof import('~icons/ep/caret-left')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpVideoPause: typeof import('~icons/ep/video-pause')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    Item: typeof import('./components/item/index.vue')['default']
    Lyric: typeof import('./components/lyric/index.vue')['default']
    Message: typeof import('./components/message/index.vue')['default']
    Mute: typeof import('./components/icon/mute.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/slider/index.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
    Voice: typeof import('./components/icon/voice.vue')['default']
  }
}

export {}
